services:
  - type: web
    name: orbitx-design
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: WTF_CSRF_ENABLED
        value: True
      - key: DATABASE_URL
        fromDatabase:
          name: orbitx-database
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TARGET_PHONE_NUMBER
        sync: false
      - key: TARGET_WHATSAPP_NUMBER
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false

databases:
  - name: orbitx-database
    databaseName: orbitx_db
    user: orbitx_user
    plan: free